---
domain: "localhost:9000"
support_basic_auth: yes

persistence_api:
  class: opentaxii.persistence.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: mysql://taxii:some_password@localhost/taxiipersist
    create_tables: yes

auth_api:
  class: opentaxii.auth.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: mysql://taxii:some_password@localhost/taxiiauth
    create_tables: yes
    secret: ILoveTheSecretStringIsIsGreatButNeedsToBeChangedFrienderino

logging:
  opentaxii: info
  root: info

hooks: misp_taxii_hooks.hooks
# Sample configuration for misp_taxii_server

zmq:
    host: localhost
    port: 50000

misp:
    url: "http://localhost"
    api: KEY

taxii:
    auth:
        username: ABC
        password: CDE
    collections:
        - collection
